### User sing up endpoint

POST http://localhost:5000/v1/user
Content-Type: application/json

{
	"name":"Ognjen Atlagic",
	"company" : "Company doo",
	"adress": "Brace Kovac 62",
	"phone":"+381694074955",
	"email": "atlagicognjen@gmail.com",
	"password":"12345678"
}

### User sing in endpoint

POST http://localhost:5000/v1/user/login
Content-Type: application/json

{
	"email": "atlagicognjen@gmail.com",
	"password":"12345678"
}

### Get user profile, private
GET http://localhost:5000/v1/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF0bGFnaWNvZ25qZW5AZ21haWwuY29tIiwiaWF0IjoxNjE0MDc1MDg4LCJleHAiOjE2MTY2NjcwODh9.giAOXyMytz531wc5NPH7XD-N5z890UoS3F7LfqOjp3c


### reset password

POST http://localhost:5000/v1/user/reset-password
Content-Type: application/json

{
	"email": "atlagicognjen@gmail.com"
}
